//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_BITMAP1                     132
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_LOADING                     156
#define IDB_LOGIN_LOADING				158
#define IDB_INGAME_LOADING              157
#define IDB_RED_NOR                     169
#define IDB_RED_HOR                     170
#define IDB_RED_HOR_C                   171
#define IDB_RED_NOR_C                   172
#define IDB_RED_PAC                     173
#define IDB_RED_PAC_C                   174
#define IDB_RED_VER                     175
#define IDB_RED_VER_C                   176
#define IDB_BLU_HOR                     177
#define IDB_GRE_HOR                     178
#define IDB_PUR_VER_C                   179
#define IDB_PUR_PAC                     180
#define IDB_PUR_PAC_C                   181
#define IDB_SUPER_C                     182
#define IDB_ORG_PAC                     183
#define IDB_ORG_HOR_C                   184
#define IDB_PUR_NOR_C                   185
#define IDB_ORG_VER                     186
#define IDB_ORG_VER_C                   187
#define IDB_PUR_HOR                     188
#define IDB_PUR_VER                     189
#define IDB_GRE_PAC_C                   190
#define IDB_GRE_VER                     191
#define IDB_PUR_NOR                     192
#define IDB_GRE_PAC                     193
#define IDB_GRE_NOR                     194
#define IDB_ORG_PAC_C                   195
#define IDB_PUR_HOR_C                   196
#define IDB_ORG_HOR                     197
#define IDB_BLU_VER_C                   198
#define IDB_ORG_NOR                     199
#define IDB_BLU_PAC_C                   200
#define IDB_ORG_NOR_C                   201
#define IDB_GRE_HOR_C                   202
#define IDB_GRE_VER_C                   203
#define IDB_SUPER                       204
#define IDB_BLU_VER                     205
#define IDB_GRE_NOR_C                   206
#define IDB_BLU_PAC                     207
#define IDB_BLU_HOR_C                   208
#define IDB_BLU_NOR_C                   209
#define IDB_BLU_NOR                     210
#define IDB_CONTAINER                   211
#define IDB_YEL_HOR                     212
#define IDB_YEL_HOR_C                   213
#define IDB_YEL_NOR                     214
#define IDB_YEL_NOR_C                   215
#define IDB_YEL_PAC                     216
#define IDB_YEL_VER                     217
#define IDB_YEL_VER_C                   218
#define IDB_YEL_PAC_C                   219
#define IDB_BLACK_BAR                   220
#define IDB_TIFFY_0                     221
#define IDB_TIFFY_1                     222
#define IDB_BLU_NOR1                    223
#define IDB_BLU_NOR2                    224
#define IDB_YEL_NOR1                    225
#define IDB_RED_NOR4                    226
#define IDB_RED_NOR2                    227
#define IDB_ORG_NOR3                    228
#define IDB_RED_NOR3                    229
#define IDB_YEL_NOR4                    230
#define IDB_PUR_NOR4                    231
#define IDB_RED_NOR1                    232
#define IDB_YEL_NOR2                    233
#define IDB_YEL_NOR3                    234
#define IDB_PUR_NOR2                    235
#define IDB_PUR_NOR3                    236
#define IDB_PUR_NOR1                    237
#define IDB_ORG_NOR2                    238
#define IDB_ORG_NOR4                    239
#define IDB_GRE_NOR4                    240
#define IDB_GRE_NOR3                    241
#define IDB_ORG_NOR1                    242
#define IDB_GRE_NOR2                    243
#define IDB_GRE_NOR1                    244
#define IDB_BLU_NOR3                    245
#define IDB_BLU_NOR4                    246
#define IDB_NOR_EXPL1                   247
#define IDB_NOR_EXPL4                   248
#define IDB_NOR_EXPL3                   249
#define IDB_NOR_EXPL2                   250
#define IDB_NOR_EXPL9                   251
#define IDB_NOR_EXPL6                   252
#define IDB_NOR_EXPL8                   253
#define IDB_NOR_EXPL5                   254
#define IDB_NOR_EXPL7                   255
#define IDB_NOR_EXPL10                  256
#define IDB_YEL_EXPL9                   257
#define IDB_RED_EXPL2                   258
#define IDB_YEL_EXPL6                   259
#define IDB_YEL_EXPL3                   260
#define IDB_YEL_EXPL7                   261
#define IDB_YEL_EXPL5                   262
#define IDB_YEL_EXPL8                   263
#define IDB_YEL_EXPL4                   264
#define IDB_YEL_EXPL2                   265
#define IDB_YEL_EXPL10                  266
#define IDB_RED_EXPL9                   267
#define IDB_YEL_EXPL1                   268
#define IDB_RED_EXPL7                   269
#define IDB_PUR_EXPL2                   270
#define IDB_BLU_EXPL1                   271
#define IDB_BLU_EXPL9                   272
#define IDB_BLU_EXPL6                   273
#define IDB_RED_EXPL5                   274
#define IDB_BLU_EXPL7                   275
#define IDB_RED_EXPL8                   276
#define IDB_GRE_EXPL10                  277
#define IDB_BLU_EXPL5                   278
#define IDB_RED_EXPL6                   279
#define IDB_GRE_EXPL4                   280
#define IDB_ORG_EXPL1                   281
#define IDB_GRE_EXPL3                   282
#define IDB_GRE_EXPL8                   283
#define IDB_PUR_EXPL9                   284
#define IDB_ORG_EXPL2                   285
#define IDB_ORG_EXPL4                   286
#define IDB_GRE_EXPL7                   287
#define IDB_RED_EXPL4                   288
#define IDB_PUR_EXPL7                   289
#define IDB_PUR_EXPL6                   290
#define IDB_PUR_EXPL3                   291
#define IDB_RED_EXPL10                  292
#define IDB_PUR_EXPL8                   293
#define IDB_PUR_EXPL1                   294
#define IDB_RED_EXPL3                   295
#define IDB_RED_EXPL1                   296
#define IDB_GRE_EXPL2                   297
#define IDB_GRE_EXPL1                   298
#define IDB_ORG_EXPL7                   299
#define IDB_ORG_EXPL10                  300
#define IDB_GRE_EXPL5                   301
#define IDB_ORG_EXPL6                   302
#define IDB_GRE_EXPL6                   303
#define IDB_ORG_EXPL5                   304
#define IDB_ORG_EXPL3                   305
#define IDB_PUR_EXPL4                   306
#define IDB_PUR_EXPL10                  307
#define IDB_GRE_EXPL9                   308
#define IDB_ORG_EXPL9                   309
#define IDB_PUR_EXPL5                   310
#define IDB_BLU_EXPL8                   311
#define IDB_ORG_EXPL8                   312
#define IDB_BLU_EXPL4                   313
#define IDB_BLU_EXPL3                   314
#define IDB_BLU_EXPL2                   315
#define IDB_BLU_EXPL10                  316
#define IDB_RED_SHAT1                   318
#define IDB_RED_SHAT2                   319
#define IDB_RED_SHAT3                   320
#define IDB_RED_SHAT4                   321
#define IDB_RED_SHAT5                   322
#define IDB_RED_SHAT6                   323
#define IDB_RED_SHAT7                   324
#define IDB_RED_SHAT8                   325
#define IDB_RED_SHAT9                   326
#define IDB_RED_SHAT10                  327
#define IDB_RED_SHAT11                  328
#define IDB_RED_SHAT12                  329
#define IDB_RED_SHAT13                  330
#define IDB_RED_SHAT14                  331
#define IDB_RED_SHAT15                  332
#define IDB_ORG_SHAT1                   333
#define IDB_ORG_SHAT2                   334
#define IDB_ORG_SHAT3                   335
#define IDB_ORG_SHAT4                   336
#define IDB_ORG_SHAT5                   337
#define IDB_ORG_SHAT6                   338
#define IDB_ORG_SHAT7                   339
#define IDB_ORG_SHAT8                   340
#define IDB_ORG_SHAT9                   341
#define IDB_ORG_SHAT10                  342
#define IDB_ORG_SHAT11                  343
#define IDB_ORG_SHAT12                  344
#define IDB_ORG_SHAT13                  345
#define IDB_ORG_SHAT14                  346
#define IDB_ORG_SHAT15                  347
#define IDB_YEL_SHAT1                   348
#define IDB_YEL_SHAT2                   349
#define IDB_YEL_SHAT3                   350
#define IDB_YEL_SHAT4                   351
#define IDB_YEL_SHAT5                   352
#define IDB_YEL_SHAT6                   353
#define IDB_YEL_SHAT7                   354
#define IDB_YEL_SHAT8                   355
#define IDB_YEL_SHAT9                   356
#define IDB_YEL_SHAT10                  357
#define IDB_YEL_SHAT11                  358
#define IDB_YEL_SHAT12                  359
#define IDB_YEL_SHAT13                  360
#define IDB_YEL_SHAT14                  361
#define IDB_YEL_SHAT15                  362
#define IDB_GRE_SHAT1                   363
#define IDB_GRE_SHAT2                   364
#define IDB_GRE_SHAT3                   365
#define IDB_GRE_SHAT4                   366
#define IDB_GRE_SHAT5                   367
#define IDB_GRE_SHAT6                   368
#define IDB_GRE_SHAT7                   369
#define IDB_GRE_SHAT8                   370
#define IDB_GRE_SHAT9                   371
#define IDB_GRE_SHAT10                  372
#define IDB_GRE_SHAT11                  373
#define IDB_GRE_SHAT12                  374
#define IDB_GRE_SHAT13                  375
#define IDB_GRE_SHAT14                  376
#define IDB_GRE_SHAT15                  377
#define IDB_BLU_SHAT1                   378
#define IDB_BLU_SHAT2                   379
#define IDB_BLU_SHAT3                   380
#define IDB_BLU_SHAT4                   381
#define IDB_BLU_SHAT5                   382
#define IDB_BLU_SHAT6                   383
#define IDB_BLU_SHAT7                   384
#define IDB_BLU_SHAT8                   385
#define IDB_BLU_SHAT9                   386
#define IDB_BLU_SHAT10                  387
#define IDB_BLU_SHAT11                  388
#define IDB_BLU_SHAT12                  389
#define IDB_BLU_SHAT13                  390
#define IDB_BLU_SHAT14                  391
#define IDB_BLU_SHAT15                  392
#define IDB_PUR_SHAT1                   393
#define IDB_PUR_SHAT2                   394
#define IDB_PUR_SHAT3                   395
#define IDB_PUR_SHAT4                   396
#define IDB_PUR_SHAT5                   397
#define IDB_PUR_SHAT6                   398
#define IDB_PUR_SHAT7                   399
#define IDB_PUR_SHAT8                   400
#define IDB_PUR_SHAT9                   401
#define IDB_PUR_SHAT10                  402
#define IDB_PUR_SHAT11                  403
#define IDB_PUR_SHAT12                  404
#define IDB_PUR_SHAT13                  405
#define IDB_PUR_SHAT14                  406
#define IDB_PUR_SHAT15                  407
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775
#define IDB_TIFFY_2						32776
#define IDB_TIFFY_3						32777
#define IDB_TIFFY_4						32778
#define IDB_TIFFY_5						32779
#define IDB_TIFFY_6						32780
#define IDB_TIFFY_7						32781
#define IDB_TIFFY_8						32782
#define IDB_TIFFY_9						32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
