//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDB_STAGE_BUTTON_BLUE			105
#define IDB_STAGE_BUTTON_GREY			106
#define IDB_STAGE_BUTTON_RED			107
#define IDB_STAGE_BUTTON_YELLOW			108
#define IDB_STAGE_BUTTON_GREEN			112
#define IDB_TOFFEE_1					109
#define IDB_TOFFEE_2					110
#define IDB_TOFFEE_3					111
#define IDB_TOFFEE_4					113
#define IDB_TOFFEE_5					114
#define IDB_TOFFEE_6					115
#define IDB_0_1                         116
#define IDB_1_1                         117
#define IDB_2_1                         118
#define IDB_3_1                         119
#define IDB_4_1                         120
#define IDB_5_1                         121
#define IDB_6_1                         122
#define IDB_7_1                         123
#define IDB_8_1                         124
#define IDB_9_1							125
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_BITMAP1                     132
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_LOADING                     156
#define IDB_LOGIN_LOADING				158
#define IDB_INGAME_LOADING              157
#define IDB_RED_NOR                     169
#define IDB_RED_HOR                     170
#define IDB_RED_HOR_C                   171
#define IDB_RED_NOR_C                   172
#define IDB_RED_PAC                     173
#define IDB_RED_PAC_C                   174
#define IDB_RED_VER                     175
#define IDB_RED_VER_C                   176
#define IDB_BLU_HOR                     177
#define IDB_GRE_HOR                     178
#define IDB_PUR_VER_C                   179
#define IDB_PUR_PAC                     180
#define IDB_PUR_PAC_C                   181
#define IDB_SUPER_C                     182
#define IDB_ORG_PAC                     183
#define IDB_ORG_HOR_C                   184
#define IDB_PUR_NOR_C                   185
#define IDB_ORG_VER                     186
#define IDB_ORG_VER_C                   187
#define IDB_PUR_HOR                     188
#define IDB_PUR_VER                     189
#define IDB_GRE_PAC_C                   190
#define IDB_GRE_VER                     191
#define IDB_PUR_NOR                     192
#define IDB_GRE_PAC                     193
#define IDB_GRE_NOR                     194
#define IDB_ORG_PAC_C                   195
#define IDB_PUR_HOR_C                   196
#define IDB_ORG_HOR                     197
#define IDB_BLU_VER_C                   198
#define IDB_ORG_NOR                     199
#define IDB_BLU_PAC_C                   200
#define IDB_ORG_NOR_C                   201
#define IDB_GRE_HOR_C                   202
#define IDB_GRE_VER_C                   203
#define IDB_SUPER                       204
#define IDB_BLU_VER                     205
#define IDB_GRE_NOR_C                   206
#define IDB_BLU_PAC                     207
#define IDB_BLU_HOR_C                   208
#define IDB_BLU_NOR_C                   209
#define IDB_BLU_NOR                     210
#define IDB_CONTAINER                   211
#define IDB_YEL_HOR                     212
#define IDB_YEL_HOR_C                   213
#define IDB_YEL_NOR                     214
#define IDB_YEL_NOR_C                   215
#define IDB_YEL_PAC                     216
#define IDB_YEL_VER                     217
#define IDB_YEL_VER_C                   218
#define IDB_YEL_PAC_C                   219
#define IDB_BLACK_BAR                   220
#define IDB_TIFFY_0                     221
#define IDB_TIFFY_1                     222
#define IDB_BLU_NOR1                    223
#define IDB_BLU_NOR2                    224
#define IDB_YEL_NOR1                    225
#define IDB_RED_NOR4                    226
#define IDB_RED_NOR2                    227
#define IDB_ORG_NOR3                    228
#define IDB_RED_NOR3                    229
#define IDB_YEL_NOR4                    230
#define IDB_PUR_NOR4                    231
#define IDB_RED_NOR1                    232
#define IDB_YEL_NOR2                    233
#define IDB_YEL_NOR3                    234
#define IDB_PUR_NOR2                    235
#define IDB_PUR_NOR3                    236
#define IDB_PUR_NOR1                    237
#define IDB_ORG_NOR2                    238
#define IDB_ORG_NOR4                    239
#define IDB_GRE_NOR4                    240
#define IDB_GRE_NOR3                    241
#define IDB_ORG_NOR1                    242
#define IDB_GRE_NOR2                    243
#define IDB_GRE_NOR1                    244
#define IDB_BLU_NOR3                    245
#define IDB_BLU_NOR4                    246
#define IDB_NOR_EXPL1                   247
#define IDB_NOR_EXPL4                   248
#define IDB_NOR_EXPL3                   249
#define IDB_NOR_EXPL2                   250
#define IDB_NOR_EXPL9                   251
#define IDB_NOR_EXPL6                   252
#define IDB_NOR_EXPL8                   253
#define IDB_NOR_EXPL5                   254
#define IDB_NOR_EXPL7                   255
#define IDB_NOR_EXPL10                  256
#define IDB_YEL_EXPL9                   257
#define IDB_RED_EXPL2                   258
#define IDB_YEL_EXPL6                   259
#define IDB_YEL_EXPL3                   260
#define IDB_YEL_EXPL7                   261
#define IDB_YEL_EXPL5                   262
#define IDB_YEL_EXPL8                   263
#define IDB_YEL_EXPL4                   264
#define IDB_YEL_EXPL2                   265
#define IDB_YEL_EXPL10                  266
#define IDB_RED_EXPL9                   267
#define IDB_YEL_EXPL1                   268
#define IDB_RED_EXPL7                   269
#define IDB_PUR_EXPL2                   270
#define IDB_BLU_EXPL1                   271
#define IDB_BLU_EXPL9                   272
#define IDB_BLU_EXPL6                   273
#define IDB_RED_EXPL5                   274
#define IDB_BLU_EXPL7                   275
#define IDB_RED_EXPL8                   276
#define IDB_GRE_EXPL10                  277
#define IDB_BLU_EXPL5                   278
#define IDB_RED_EXPL6                   279
#define IDB_GRE_EXPL4                   280
#define IDB_ORG_EXPL1                   281
#define IDB_GRE_EXPL3                   282
#define IDB_GRE_EXPL8                   283
#define IDB_PUR_EXPL9                   284
#define IDB_ORG_EXPL2                   285
#define IDB_ORG_EXPL4                   286
#define IDB_GRE_EXPL7                   287
#define IDB_RED_EXPL4                   288
#define IDB_PUR_EXPL7                   289
#define IDB_PUR_EXPL6                   290
#define IDB_PUR_EXPL3                   291
#define IDB_RED_EXPL10                  292
#define IDB_PUR_EXPL8                   293
#define IDB_PUR_EXPL1                   294
#define IDB_RED_EXPL3                   295
#define IDB_RED_EXPL1                   296
#define IDB_GRE_EXPL2                   297
#define IDB_GRE_EXPL1                   298
#define IDB_ORG_EXPL7                   299
#define IDB_ORG_EXPL10                  300
#define IDB_GRE_EXPL5                   301
#define IDB_ORG_EXPL6                   302
#define IDB_GRE_EXPL6                   303
#define IDB_ORG_EXPL5                   304
#define IDB_ORG_EXPL3                   305
#define IDB_PUR_EXPL4                   306
#define IDB_PUR_EXPL10                  307
#define IDB_GRE_EXPL9                   308
#define IDB_ORG_EXPL9                   309
#define IDB_PUR_EXPL5                   310
#define IDB_BLU_EXPL8                   311
#define IDB_ORG_EXPL8                   312
#define IDB_BLU_EXPL4                   313
#define IDB_BLU_EXPL3                   314
#define IDB_BLU_EXPL2                   315
#define IDB_BLU_EXPL10                  316
#define IDB_RED_SHAT1                   318
#define IDB_RED_SHAT2                   319
#define IDB_RED_SHAT3                   320
#define IDB_RED_SHAT4                   321
#define IDB_RED_SHAT5                   322
#define IDB_RED_SHAT6                   323
#define IDB_RED_SHAT7                   324
#define IDB_RED_SHAT8                   325
#define IDB_RED_SHAT9                   326
#define IDB_RED_SHAT10                  327
#define IDB_RED_SHAT11                  328
#define IDB_RED_SHAT12                  329
#define IDB_RED_SHAT13                  330
#define IDB_RED_SHAT14                  331
#define IDB_RED_SHAT15                  332
#define IDB_ORG_SHAT1                   333
#define IDB_ORG_SHAT2                   334
#define IDB_ORG_SHAT3                   335
#define IDB_ORG_SHAT4                   336
#define IDB_ORG_SHAT5                   337
#define IDB_ORG_SHAT6                   338
#define IDB_ORG_SHAT7                   339
#define IDB_ORG_SHAT8                   340
#define IDB_ORG_SHAT9                   341
#define IDB_ORG_SHAT10                  342
#define IDB_ORG_SHAT11                  343
#define IDB_ORG_SHAT12                  344
#define IDB_ORG_SHAT13                  345
#define IDB_ORG_SHAT14                  346
#define IDB_ORG_SHAT15                  347
#define IDB_YEL_SHAT1                   348
#define IDB_YEL_SHAT2                   349
#define IDB_YEL_SHAT3                   350
#define IDB_YEL_SHAT4                   351
#define IDB_YEL_SHAT5                   352
#define IDB_YEL_SHAT6                   353
#define IDB_YEL_SHAT7                   354
#define IDB_YEL_SHAT8                   355
#define IDB_YEL_SHAT9                   356
#define IDB_YEL_SHAT10                  357
#define IDB_YEL_SHAT11                  358
#define IDB_YEL_SHAT12                  359
#define IDB_YEL_SHAT13                  360
#define IDB_YEL_SHAT14                  361
#define IDB_YEL_SHAT15                  362
#define IDB_GRE_SHAT1                   363
#define IDB_GRE_SHAT2                   364
#define IDB_GRE_SHAT3                   365
#define IDB_GRE_SHAT4                   366
#define IDB_GRE_SHAT5                   367
#define IDB_GRE_SHAT6                   368
#define IDB_GRE_SHAT7                   369
#define IDB_GRE_SHAT8                   370
#define IDB_GRE_SHAT9                   371
#define IDB_GRE_SHAT10                  372
#define IDB_GRE_SHAT11                  373
#define IDB_GRE_SHAT12                  374
#define IDB_GRE_SHAT13                  375
#define IDB_GRE_SHAT14                  376
#define IDB_GRE_SHAT15                  377
#define IDB_BLU_SHAT1                   378
#define IDB_BLU_SHAT2                   379
#define IDB_BLU_SHAT3                   380
#define IDB_BLU_SHAT4                   381
#define IDB_BLU_SHAT5                   382
#define IDB_BLU_SHAT6                   383
#define IDB_BLU_SHAT7                   384
#define IDB_BLU_SHAT8                   385
#define IDB_BLU_SHAT9                   386
#define IDB_BLU_SHAT10                  387
#define IDB_BLU_SHAT11                  388
#define IDB_BLU_SHAT12                  389
#define IDB_BLU_SHAT13                  390
#define IDB_BLU_SHAT14                  391
#define IDB_BLU_SHAT15                  392
#define IDB_PUR_SHAT1                   393
#define IDB_PUR_SHAT2                   394
#define IDB_PUR_SHAT3                   395
#define IDB_PUR_SHAT4                   396
#define IDB_PUR_SHAT5                   397
#define IDB_PUR_SHAT6                   398
#define IDB_PUR_SHAT7                   399
#define IDB_PUR_SHAT8                   400
#define IDB_PUR_SHAT9                   401
#define IDB_PUR_SHAT10                  402
#define IDB_PUR_SHAT11                  403
#define IDB_PUR_SHAT12                  404
#define IDB_PUR_SHAT13                  405
#define IDB_PUR_SHAT14                  406
#define IDB_PUR_SHAT15                  407
#define IDB_TIFFY_2						408
#define IDB_TIFFY_3						409
#define IDB_TIFFY_4						410
#define IDB_TIFFY_5						411
#define IDB_TIFFY_6						412
#define IDB_TIFFY_7						413
#define IDB_TIFFY_8						414
#define IDB_TIFFY_9						415
#define IDB_PLAYBUTTON_1				416
#define IDB_PLAYBUTTON_2				417
#define IDB_PLAYBUTTON_3				418
#define IDB_PLAYBUTTON_4				419
#define IDB_PLAYBUTTON_5				420
#define IDB_PLAYBUTTON_6				421
#define IDB_PLAYBUTTON_7				422
#define IDB_PLAYBUTTON_8				423
#define IDB_PLAYBUTTON_9				424
#define IDB_PLAYBUTTON_10				425
#define IDB_PLAYBUTTON_11				426
#define IDB_PLAYBUTTON_12				427
#define IDB_RED_VEXPL1                  428
#define IDB_RED_VEXPL2                  429
#define IDB_RED_VEXPL3                  430
#define IDB_RED_VEXPL4                  431
#define IDB_RED_VEXPL5                  432
#define IDB_RED_VEXPL6                  433
#define IDB_RED_VEXPL7                  434
#define IDB_RED_VEXPL8                  435
#define IDB_RED_VEXPL9                  436
#define IDB_RED_VEXPL10                 437
#define IDB_RED_VEXPL11                 438
#define IDB_RED_VEXPL12                 439
#define IDB_RED_VEXPL13                 440
#define IDB_RED_VEXPL14                 441
#define IDB_RED_VEXPL15                 442
#define IDB_RED_VEXPL16                 443
#define IDB_RED_VEXPL17                 444
#define IDB_RED_VEXPL18                 445
#define IDB_RED_VEXPL19                 446
#define IDB_RED_VEXPL20                 447
#define IDB_RED_VEXPL21                 448
#define IDB_RED_VEXPL22                 449
#define IDB_RED_VEXPL23                 450
#define IDB_RED_VEXPL24                 451
#define IDB_RED_VEXPL25                 452
#define IDB_RED_VEXPL26                 453
#define IDB_RED_VEXPL27                 454
#define IDB_RED_VEXPL28                 455
#define IDB_RED_VEXPL29                 456
#define IDB_RED_VEXPL30                 457
#define IDB_RED_HEXPL1                  458
#define IDB_RED_HEXPL2                  459
#define IDB_RED_HEXPL3                  460
#define IDB_RED_HEXPL4                  461
#define IDB_RED_HEXPL5                  462
#define IDB_RED_HEXPL6                  463
#define IDB_RED_HEXPL7                  464
#define IDB_RED_HEXPL8                  465
#define IDB_RED_HEXPL9                  466
#define IDB_RED_HEXPL10                 467
#define IDB_RED_HEXPL11                 468
#define IDB_RED_HEXPL12                 469
#define IDB_RED_HEXPL13                 470
#define IDB_RED_HEXPL14                 471
#define IDB_RED_HEXPL15                 472
#define IDB_RED_HEXPL16                 473
#define IDB_RED_HEXPL17                 474
#define IDB_RED_HEXPL18                 475
#define IDB_RED_HEXPL19                 476
#define IDB_RED_HEXPL20                 477
#define IDB_RED_HEXPL21                 478
#define IDB_RED_HEXPL22                 479
#define IDB_RED_HEXPL23                 480
#define IDB_RED_HEXPL24                 481
#define IDB_RED_HEXPL25                 482
#define IDB_RED_HEXPL26                 483
#define IDB_RED_HEXPL27                 484
#define IDB_RED_HEXPL28                 485
#define IDB_RED_HEXPL29                 486
#define IDB_RED_HEXPL30                 487
#define IDB_ORG_VEXPL1                  488
#define IDB_ORG_VEXPL2                  489
#define IDB_ORG_VEXPL3                  490
#define IDB_ORG_VEXPL4                  491
#define IDB_ORG_VEXPL5                  492
#define IDB_ORG_VEXPL6                  493
#define IDB_ORG_VEXPL7                  494
#define IDB_ORG_VEXPL8                  495
#define IDB_ORG_VEXPL9                  496
#define IDB_ORG_VEXPL10                 497
#define IDB_ORG_VEXPL11                 498
#define IDB_ORG_VEXPL12                 499
#define IDB_ORG_VEXPL13                 500
#define IDB_ORG_VEXPL14                 501
#define IDB_ORG_VEXPL15                 502
#define IDB_ORG_VEXPL16                 503
#define IDB_ORG_VEXPL17                 504
#define IDB_ORG_VEXPL18                 505
#define IDB_ORG_VEXPL19                 506
#define IDB_ORG_VEXPL20                 507
#define IDB_ORG_VEXPL21                 508
#define IDB_ORG_VEXPL22                 509
#define IDB_ORG_VEXPL23                 510
#define IDB_ORG_VEXPL24                 511
#define IDB_ORG_VEXPL25                 512
#define IDB_ORG_VEXPL26                 513
#define IDB_ORG_VEXPL27                 514
#define IDB_ORG_VEXPL28                 515
#define IDB_ORG_VEXPL29                 516
#define IDB_ORG_VEXPL30                 517
#define IDB_ORG_HEXPL1                  518
#define IDB_ORG_HEXPL2                  519
#define IDB_ORG_HEXPL3                  520
#define IDB_ORG_HEXPL4                  521
#define IDB_ORG_HEXPL5                  522
#define IDB_ORG_HEXPL6                  523
#define IDB_ORG_HEXPL7                  524
#define IDB_ORG_HEXPL8                  525
#define IDB_ORG_HEXPL9                  526
#define IDB_ORG_HEXPL10                 527
#define IDB_ORG_HEXPL11                 528
#define IDB_ORG_HEXPL12                 529
#define IDB_ORG_HEXPL13                 530
#define IDB_ORG_HEXPL14                 531
#define IDB_ORG_HEXPL15                 532
#define IDB_ORG_HEXPL16                 533
#define IDB_ORG_HEXPL17                 534
#define IDB_ORG_HEXPL18                 535
#define IDB_ORG_HEXPL19                 536
#define IDB_ORG_HEXPL20                 537
#define IDB_ORG_HEXPL21                 538
#define IDB_ORG_HEXPL22                 539
#define IDB_ORG_HEXPL23                 540
#define IDB_ORG_HEXPL24                 541
#define IDB_ORG_HEXPL25                 542
#define IDB_ORG_HEXPL26                 543
#define IDB_ORG_HEXPL27                 544
#define IDB_ORG_HEXPL28                 545
#define IDB_ORG_HEXPL29                 546
#define IDB_ORG_HEXPL30                 547
#define IDB_YEL_VEXPL1                  548
#define IDB_YEL_VEXPL2                  549
#define IDB_YEL_VEXPL3                  550
#define IDB_YEL_VEXPL4                  551
#define IDB_YEL_VEXPL5                  552
#define IDB_YEL_VEXPL6                  553
#define IDB_YEL_VEXPL7                  554
#define IDB_YEL_VEXPL8                  555
#define IDB_YEL_VEXPL9                  556
#define IDB_YEL_VEXPL10                 557
#define IDB_YEL_VEXPL11                 558
#define IDB_YEL_VEXPL12                 559
#define IDB_YEL_VEXPL13                 560
#define IDB_YEL_VEXPL14                 561
#define IDB_YEL_VEXPL15                 562
#define IDB_YEL_VEXPL16                 563
#define IDB_YEL_VEXPL17                 564
#define IDB_YEL_VEXPL18                 565
#define IDB_YEL_VEXPL19                 566
#define IDB_YEL_VEXPL20                 567
#define IDB_YEL_VEXPL21                 568
#define IDB_YEL_VEXPL22                 569
#define IDB_YEL_VEXPL23                 570
#define IDB_YEL_VEXPL24                 571
#define IDB_YEL_VEXPL25                 572
#define IDB_YEL_VEXPL26                 573
#define IDB_YEL_VEXPL27                 574
#define IDB_YEL_VEXPL28                 575
#define IDB_YEL_VEXPL29                 576
#define IDB_YEL_VEXPL30                 577
#define IDB_YEL_HEXPL1                  578
#define IDB_YEL_HEXPL2                  579
#define IDB_YEL_HEXPL3                  580
#define IDB_YEL_HEXPL4                  581
#define IDB_YEL_HEXPL5                  582
#define IDB_YEL_HEXPL6                  583
#define IDB_YEL_HEXPL7                  584
#define IDB_YEL_HEXPL8                  585
#define IDB_YEL_HEXPL9                  586
#define IDB_YEL_HEXPL10                 587
#define IDB_YEL_HEXPL11                 588
#define IDB_YEL_HEXPL12                 589
#define IDB_YEL_HEXPL13                 590
#define IDB_YEL_HEXPL14                 591
#define IDB_YEL_HEXPL15                 592
#define IDB_YEL_HEXPL16                 593
#define IDB_YEL_HEXPL17                 594
#define IDB_YEL_HEXPL18                 595
#define IDB_YEL_HEXPL19                 596
#define IDB_YEL_HEXPL20                 597
#define IDB_YEL_HEXPL21                 598
#define IDB_YEL_HEXPL22                 599
#define IDB_YEL_HEXPL23                 600
#define IDB_YEL_HEXPL24                 601
#define IDB_YEL_HEXPL25                 602
#define IDB_YEL_HEXPL26                 603
#define IDB_YEL_HEXPL27                 604
#define IDB_YEL_HEXPL28                 605
#define IDB_YEL_HEXPL29                 606
#define IDB_YEL_HEXPL30                 607
#define IDB_GRE_VEXPL1                  608
#define IDB_GRE_VEXPL2                  609
#define IDB_GRE_VEXPL3                  610
#define IDB_GRE_VEXPL4                  611
#define IDB_GRE_VEXPL5                  612
#define IDB_GRE_VEXPL6                  613
#define IDB_GRE_VEXPL7                  614
#define IDB_GRE_VEXPL8                  615
#define IDB_GRE_VEXPL9                  616
#define IDB_GRE_VEXPL10                 617
#define IDB_GRE_VEXPL11                 618
#define IDB_GRE_VEXPL12                 619
#define IDB_GRE_VEXPL13                 620
#define IDB_GRE_VEXPL14                 621
#define IDB_GRE_VEXPL15                 622
#define IDB_GRE_VEXPL16                 623
#define IDB_GRE_VEXPL17                 624
#define IDB_GRE_VEXPL18                 625
#define IDB_GRE_VEXPL19                 626
#define IDB_GRE_VEXPL20                 627
#define IDB_GRE_VEXPL21                 628
#define IDB_GRE_VEXPL22                 629
#define IDB_GRE_VEXPL23                 630
#define IDB_GRE_VEXPL24                 631
#define IDB_GRE_VEXPL25                 632
#define IDB_GRE_VEXPL26                 633
#define IDB_GRE_VEXPL27                 634
#define IDB_GRE_VEXPL28                 635
#define IDB_GRE_VEXPL29                 636
#define IDB_GRE_VEXPL30                 637
#define IDB_GRE_HEXPL1                  638
#define IDB_GRE_HEXPL2                  639
#define IDB_GRE_HEXPL3                  640
#define IDB_GRE_HEXPL4                  641
#define IDB_GRE_HEXPL5                  642
#define IDB_GRE_HEXPL6                  643
#define IDB_GRE_HEXPL7                  644
#define IDB_GRE_HEXPL8                  645
#define IDB_GRE_HEXPL9                  646
#define IDB_GRE_HEXPL10                 647
#define IDB_GRE_HEXPL11                 648
#define IDB_GRE_HEXPL12                 649
#define IDB_GRE_HEXPL13                 650
#define IDB_GRE_HEXPL14                 651
#define IDB_GRE_HEXPL15                 652
#define IDB_GRE_HEXPL16                 653
#define IDB_GRE_HEXPL17                 654
#define IDB_GRE_HEXPL18                 655
#define IDB_GRE_HEXPL19                 656
#define IDB_GRE_HEXPL20                 657
#define IDB_GRE_HEXPL21                 658
#define IDB_GRE_HEXPL22                 659
#define IDB_GRE_HEXPL23                 660
#define IDB_GRE_HEXPL24                 661
#define IDB_GRE_HEXPL25                 662
#define IDB_GRE_HEXPL26                 663
#define IDB_GRE_HEXPL27                 664
#define IDB_GRE_HEXPL28                 665
#define IDB_GRE_HEXPL29                 666
#define IDB_GRE_HEXPL30                 667
#define IDB_BLU_VEXPL1                  668
#define IDB_BLU_VEXPL2                  669
#define IDB_BLU_VEXPL3                  670
#define IDB_BLU_VEXPL4                  671
#define IDB_BLU_VEXPL5                  672
#define IDB_BLU_VEXPL6                  673
#define IDB_BLU_VEXPL7                  674
#define IDB_BLU_VEXPL8                  675
#define IDB_BLU_VEXPL9                  676
#define IDB_BLU_VEXPL10                 677
#define IDB_BLU_VEXPL11                 678
#define IDB_BLU_VEXPL12                 679
#define IDB_BLU_VEXPL13                 680
#define IDB_BLU_VEXPL14                 681
#define IDB_BLU_VEXPL15                 682
#define IDB_BLU_VEXPL16                 683
#define IDB_BLU_VEXPL17                 684
#define IDB_BLU_VEXPL18                 685
#define IDB_BLU_VEXPL19                 686
#define IDB_BLU_VEXPL20                 687
#define IDB_BLU_VEXPL21                 688
#define IDB_BLU_VEXPL22                 689
#define IDB_BLU_VEXPL23                 690
#define IDB_BLU_VEXPL24                 691
#define IDB_BLU_VEXPL25                 692
#define IDB_BLU_VEXPL26                 693
#define IDB_BLU_VEXPL27                 694
#define IDB_BLU_VEXPL28                 695
#define IDB_BLU_VEXPL29                 696
#define IDB_BLU_VEXPL30                 697
#define IDB_BLU_HEXPL1                  698
#define IDB_BLU_HEXPL2                  699
#define IDB_BLU_HEXPL3                  700
#define IDB_BLU_HEXPL4                  701
#define IDB_BLU_HEXPL5                  702
#define IDB_BLU_HEXPL6                  703
#define IDB_BLU_HEXPL7                  704
#define IDB_BLU_HEXPL8                  705
#define IDB_BLU_HEXPL9                  706
#define IDB_BLU_HEXPL10                 707
#define IDB_BLU_HEXPL11                 708
#define IDB_BLU_HEXPL12                 709
#define IDB_BLU_HEXPL13                 710
#define IDB_BLU_HEXPL14                 711
#define IDB_BLU_HEXPL15                 712
#define IDB_BLU_HEXPL16                 713
#define IDB_BLU_HEXPL17                 714
#define IDB_BLU_HEXPL18                 715
#define IDB_BLU_HEXPL19                 716
#define IDB_BLU_HEXPL20                 717
#define IDB_BLU_HEXPL21                 718
#define IDB_BLU_HEXPL22                 719
#define IDB_BLU_HEXPL23                 720
#define IDB_BLU_HEXPL24                 721
#define IDB_BLU_HEXPL25                 722
#define IDB_BLU_HEXPL26                 723
#define IDB_BLU_HEXPL27                 724
#define IDB_BLU_HEXPL28                 725
#define IDB_BLU_HEXPL29                 726
#define IDB_BLU_HEXPL30                 727
#define IDB_PUR_VEXPL1                  728
#define IDB_PUR_VEXPL2                  729
#define IDB_PUR_VEXPL3                  730
#define IDB_PUR_VEXPL4                  731
#define IDB_PUR_VEXPL5                  732
#define IDB_PUR_VEXPL6                  733
#define IDB_PUR_VEXPL7                  734
#define IDB_PUR_VEXPL8                  735
#define IDB_PUR_VEXPL9                  736
#define IDB_PUR_VEXPL10                 737
#define IDB_PUR_VEXPL11                 738
#define IDB_PUR_VEXPL12                 739
#define IDB_PUR_VEXPL13                 740
#define IDB_PUR_VEXPL14                 741
#define IDB_PUR_VEXPL15                 742
#define IDB_PUR_VEXPL16                 743
#define IDB_PUR_VEXPL17                 744
#define IDB_PUR_VEXPL18                 745
#define IDB_PUR_VEXPL19                 746
#define IDB_PUR_VEXPL20                 747
#define IDB_PUR_VEXPL21                 748
#define IDB_PUR_VEXPL22                 749
#define IDB_PUR_VEXPL23                 750
#define IDB_PUR_VEXPL24                 751
#define IDB_PUR_VEXPL25                 752
#define IDB_PUR_VEXPL26                 753
#define IDB_PUR_VEXPL27                 754
#define IDB_PUR_VEXPL28                 755
#define IDB_PUR_VEXPL29                 756
#define IDB_PUR_VEXPL30                 757
#define IDB_PUR_HEXPL1                  758
#define IDB_PUR_HEXPL2                  759
#define IDB_PUR_HEXPL3                  760
#define IDB_PUR_HEXPL4                  761
#define IDB_PUR_HEXPL5                  762
#define IDB_PUR_HEXPL6                  763
#define IDB_PUR_HEXPL7                  764
#define IDB_PUR_HEXPL8                  765
#define IDB_PUR_HEXPL9                  766
#define IDB_PUR_HEXPL10                 767
#define IDB_PUR_HEXPL11                 768
#define IDB_PUR_HEXPL12                 769
#define IDB_PUR_HEXPL13                 770
#define IDB_PUR_HEXPL14                 771
#define IDB_PUR_HEXPL15                 772
#define IDB_PUR_HEXPL16                 773
#define IDB_PUR_HEXPL17                 774
#define IDB_PUR_HEXPL18                 775
#define IDB_PUR_HEXPL19                 776
#define IDB_PUR_HEXPL20                 777
#define IDB_PUR_HEXPL21                 778
#define IDB_PUR_HEXPL22                 779
#define IDB_PUR_HEXPL23                 780
#define IDB_PUR_HEXPL24                 781
#define IDB_PUR_HEXPL25                 782
#define IDB_PUR_HEXPL26                 783
#define IDB_PUR_HEXPL27                 784
#define IDB_PUR_HEXPL28                 785
#define IDB_PUR_HEXPL29                 786
#define IDB_PUR_HEXPL30                 787
#define IDB_CANDY_CRUSH_1               788
#define IDB_CANDY_CRUSH_2               789
#define IDB_CANDY_CRUSH_3               790
#define IDB_CANDY_CRUSH_4               791
#define IDB_CANDY_CRUSH_5               792
#define IDB_CANDY_CRUSH_6               793
#define IDB_CANDY_CRUSH_7               794
#define IDB_CANDY_CRUSH_8               795
#define IDB_CANDY_CRUSH_9               796
#define IDB_CANDY_CRUSH_10              797
#define IDB_CANDY_CRUSH_11              798
#define IDB_CANDY_CRUSH_12              799
#define IDB_CANDY_CRUSH_13              800
#define IDB_CANDY_CRUSH_14              801
#define IDB_CANDY_CRUSH_15              802
#define IDB_CANDY_CRUSH_16              803
#define IDB_CANDY_CRUSH_17              804
#define IDB_CANDY_CRUSH_18              805
#define IDB_CANDY_CRUSH_19              806
#define IDB_CANDY_CRUSH_20              807
#define IDB_CANDY_CRUSH_21              808
#define IDB_CANDY_CRUSH_22              809
#define IDB_CANDY_CRUSH_23              810
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
